# cmake/host-gcc.cmake


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS   "-Wall -Wextra -g3 -O0")
set(CMAKE_CXX_FLAGS "-Wall -Wextra -g3 -O0")
